# Generated by Django 3.2.9 on 2021-11-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='update',
        ),
        migrations.AddField(
            model_name='todo',
            name='today',
            field=models.CharField(default='23-11-2021', max_length=25),
        ),
    ]
