# Generated by Django 3.2.9 on 2021-11-25 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='today',
        ),
        migrations.AddField(
            model_name='todo',
            name='day',
            field=models.DateField(default=datetime.datetime(2021, 11, 25, 14, 33, 53, 796296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='when',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
