# Generated by Django 3.2.9 on 2021-11-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211123_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='today',
            field=models.CharField(default='24-11-2021', max_length=25),
        ),
        migrations.AlterField(
            model_name='todo',
            name='today',
            field=models.CharField(default='24-11-2021', max_length=25),
        ),
    ]
