# Generated by Django 3.2.9 on 2021-11-25 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20211125_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
