# Generated by Django 3.2.9 on 2021-12-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='when',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
